/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/untitled.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Building (props) {
  const { nodes, materials } = useGLTF('./models/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.002, 0.034, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[0, 0, 2.302]}>
          <mesh geometry={nodes.Mesh002.geometry} material={materials.Emm} />
          <mesh geometry={nodes.Mesh002_1.geometry} material={materials.Default} />
        </group>
        <group position={[0, 0, 4.605]}>
          <mesh geometry={nodes.Mesh003.geometry} material={materials.Emm} />
          <mesh geometry={nodes.Mesh003_1.geometry} material={materials.Default} />
        </group>
        <group position={[0, 0, 6.907]}>
          <mesh geometry={nodes.Mesh004.geometry} material={materials.Emm} />
          <mesh geometry={nodes.Mesh004_1.geometry} material={materials.Default} />
        </group>
        <group position={[0, 0, 9.209]}>
          <mesh geometry={nodes.Mesh005.geometry} material={materials.Emm} />
          <mesh geometry={nodes.Mesh005_1.geometry} material={materials.Default} />
        </group>
        <group position={[0, 0, 11.512]}>
          <mesh geometry={nodes.Mesh006.geometry} material={materials.Emm} />
          <mesh geometry={nodes.Mesh006_1.geometry} material={materials.Default} />
        </group>
        <group position={[0, 0, 13.814]}>
          <mesh geometry={nodes.Mesh007.geometry} material={materials.Emm} />
          <mesh geometry={nodes.Mesh007_1.geometry} material={materials.Default} />
        </group>
        <group position={[0, 0, 16.117]}>
          <mesh geometry={nodes.Mesh008.geometry} material={materials.Emm} />
          <mesh geometry={nodes.Mesh008_1.geometry} material={materials.Default} />
        </group>
        <mesh geometry={nodes.polySurface19.geometry} material={materials.Default} />
        <mesh geometry={nodes.Mesh001.geometry} material={materials.Emm} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.Default} />
        <mesh geometry={nodes.Mesh009.geometry} material={materials.Default} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials.Emm} />
        <mesh geometry={nodes.polySurface20.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface22.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface24.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface26.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface28.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface30.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface32.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface34.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface36.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface38.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface40.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface42.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface44.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface46.geometry} material={materials.conc} />
        <mesh geometry={nodes.polySurface47.geometry} material={materials.conc} />
      </group>
      <mesh geometry={nodes.pPlane1.geometry} material={materials.Default} position={[0.038, 0.229, -0.015]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.pPlane2.geometry} material={materials.Default} position={[0.038, 0.197, -0.015]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.pPlane3.geometry} material={materials.Default} position={[0.038, 0.164, -0.015]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.pPlane4.geometry} material={materials.Default} position={[0.038, 0.132, -0.015]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.pPlane5.geometry} material={materials.Default} position={[0.038, 0.1, -0.015]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.pPlane6.geometry} material={materials.Default} position={[0.038, 0.068, -0.015]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.pPlane7.geometry} material={materials.Default} position={[0.038, 0.035, -0.015]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.pPlane15.geometry} material={materials.Default} position={[-0.025, 0.035, -0.037]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.004, 0.01]} />
      <mesh geometry={nodes.pPlane16.geometry} material={materials.Default} position={[-0.025, 0.068, -0.037]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.004, 0.01]} />
      <mesh geometry={nodes.pPlane17.geometry} material={materials.Default} position={[-0.025, 0.1, -0.037]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.004, 0.01]} />
      <mesh geometry={nodes.pPlane18.geometry} material={materials.Default} position={[-0.025, 0.229, -0.037]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.004, 0.01]} />
      <mesh geometry={nodes.pPlane19.geometry} material={materials.Default} position={[-0.025, 0.197, -0.037]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.004, 0.01]} />
      <mesh geometry={nodes.pPlane20.geometry} material={materials.Default} position={[-0.025, 0.132, -0.037]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.004, 0.01]} />
      <mesh geometry={nodes.pPlane21.geometry} material={materials.Default} position={[-0.025, 0.164, -0.037]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.004, 0.01]} />
      <mesh geometry={nodes.pPlane27.geometry} material={materials.Default} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.pPlane28.geometry} material={materials.Default} position={[-0.014, 0, 0.005]} rotation={[Math.PI / 2, 0, Math.PI / 4]} scale={0.01} />
      <mesh geometry={nodes.pPlane29.geometry} material={materials.Default} position={[0.031, 0, 0.002]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.009, 0.01]} />
      <mesh geometry={nodes.pPlane30.geometry} material={materials.Default} position={[-0.003, 0, 0.002]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.009, 0.01]} />
      <mesh geometry={nodes.pPlane32.geometry} material={materials.Default} position={[0.003, 0, -0.029]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.01, 0.009, 0.01]} />
      <mesh geometry={nodes.pPlane33.geometry} material={materials.Default} position={[0.003, 0, 0.005]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.01, 0.009, 0.01]} />
      <mesh geometry={nodes.pPlane34.geometry} material={materials.Default} position={[0.002, 0, 0.069]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.pPlane35.geometry} material={materials.conc} rotation={[Math.PI / 2, 0, 0]} scale={0.013} />
    </group>
  )
}

useGLTF.preload('./models/untitled.glb')
